# This is a basic workflow to help you get started with Actions

name: Release mode
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build-ios:
    needs: install-and-test
    runs-on: [self-hosted, macos]
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Install pod dependencies
        run: |
          cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace GithubActions.xcworkspace -scheme GithubActions archive -archivePath GithubActions.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./GithubActions.xcarchive -exportPath . -exportOptionsPlist GithubActions/Info.plist
          mv GithubActions.ipa ../GithubActions.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: GithubActions.ipa
          path: ios/build/
